.TH bemacs 1 "Barry Scott"
.ds )H Barry Scott
.SH NAME
bemacs \- Barry's emacs style editor for X.
.SH SYNOPSIS
.B bemacs
[
.I command-line-options
[
.I file...
]

.SH DESCRIPTION
The primary documentation for
.I bemacs
is available in HTML format. This man page only lists a subset of
.I bemacs
command line options. The HTML documentation can be found in URL:

file:/opt/corp/contrib/pkg/bemacs/docs/emacs_documentation.htm
.br
or
.br
http://47.96.0.200/BEmacs/documentation/emacs-documentation.htm

The first time the
.I bemacs
command is used a new bemacs server process is started and the command line arguments are
handled by the server. After that the
.I bemacs
command passes the command line arguments to the running server to handle.

The default behaviour of
.I bemacs
is to open each
.I file
on the command line ready for editing.

.SH Options and arguments
.I bemacs
recognises the following options and arguments:

.RS
.ifn .TP 10
.ift .TP 15
.CR -cd
cause the bemacs server to change directory to match the current working directory of the shell.

.TP
.CR -line=number
Start editing at line
.I number.
This option applies to the next
.I file
argument.

.TP
.CR +number
Start editing at line
.I number.
This option applies to the next
.I file
argument. This option is provided for compatibility with the standard
.B vi
command line
.B +
option.

.TP
.CR file
Specify the file or files to be edited.

.RE


.SH EXAMPLES
Tell
.I bemacs
to start editing
.B driver.cpp
at line number
.B 73

.ss 18
.RS
bemacs +73 driver.cpp
.RE
.SH X Resources

Here are the X resources that
.I bemacs
uses.

BEmacs*foreground: black
.br
BEmacs*background: grey75
.br
BEmacs.geometry: 100x40
.br
BEmacs.displayToolBar:	true
.br
BEmacs.displayScrollBars:	true
.br
BEmacs.displayStatusBar:	true
.br
BEmacs.textFont: -adobe-courier-medium-r-normal--14-120-100-100-m-100-iso8859-1
.br
BEmacs.specialFont: -dec-terminal-medium-r-normal--14-*-*-*-c-80-dec-dectech
.br
BEmacs.normalForeground: black
.br
BEmacs.normalBackground: white
.br
BEmacs.normalUnderline: no
.br
BEmacs.modelineForeground: yellow
.br
BEmacs.modelineBackground: blue
.br
BEmacs.modelineUnderline: no
.br
BEmacs.highlightForeground: black
.br
BEmacs.highlightBackground: grey75
.br
BEmacs.highlightUnderline: no
.br
!BEmacs.cursorForeground:
.br
!BEmacs.cursorBackground:
.br
!BEmacs.wordForeground:
.br
!BEmacs.wordBackground:
.br
!BEmacs.wordUnderline:
.br
BEmacs.stringForeground: purple
.br
BEmacs.stringBackground: white
.br
BEmacs.stringUnderline: no
.br
BEmacs.commentForeground: darkgreen
.br
BEmacs.commentBackground: white
.br
BEmacs.commentUnderline: no
.br
BEmacs.keyword1Foreground: blue
.br
BEmacs.keyword1Background: white
.br
BEmacs.keyword1Underline: yes
.br
BEmacs.keyword2Foreground: purple
.br
BEmacs.keyword2Background: white
.br
BEmacs.keyword2Underline: yes
.br
BEmacs.keyword3Foreground: red
.br
BEmacs.keyword3Background: white
.br
BEmacs.keyword3Underline: yes
.br
BEmacs.user1Foreground: red
.br
BEmacs.user1Background: white
.br
BEmacs.user1Underline: yes
.br
BEmacs.user2Foreground: blue
.br
BEmacs.user2Background: white
.br
BEmacs.user2Underline: no
.br
BEmacs.user3Foreground: green
.br
BEmacs.user3Background: white
.br
BEmacs.user3Underline: no
.br
BEmacs.user4Foreground: red
.br
BEmacs.user4Background: white
.br
BEmacs.user4Underline: no
.br
BEmacs.user5Foreground: black
.br
BEmacs.user5Background: white
.br
BEmacs.user5Underline: no
.br
BEmacs.user6Foreground: black
.br
BEmacs.user6Background: white
.br
BEmacs.user6Underline: no
.br
BEmacs.user7Foreground: black
.br
BEmacs.user7Background: white
.br
BEmacs.user7Underline: no
.br
BEmacs.user8Foreground: black
.br
BEmacs.user8Background: white
.br
BEmacs.user8Underline: no
.br
!
.br
!	Indicators
.br
!
.br
BEmacs*status_bar_form.?.?.background: white
.br

.br
!BEmacs.*.line_number_text.foreground: black
.br
!BEmacs.*.line_number_text.background: white
.br
!BEmacs.*.column_number_text.foreground: black
.br
!BEmacs.*.column_number_text.background: white
.br
!BEmacs.*.read_only_text.foreground: red
.br
!BEmacs.*.read_only_text.background: white
.br
!BEmacs.*.over_strike_text.foreground: blue
.br
!BEmacs.*.over_strike_text.background: white
.br
!BEmacs.*.tool_bar_rowcolumn.?.foreground: black
.br
BEmacs*tool_bar_rowcolumn.spacing: 0
.br
!
.br
!	Give F10 back to Emacs as an usable key
.br
!
.br
BEmacs.main_window.menu_bar.menuAccelerator: Alt<Key>F10
.br


.SH HISTORY
.I bemacs
is Barry's Emacs which has been in development since 1981.
.I bemacs
was inspired by James Gosling's Emacs and using a variant of Gosling's Mock Lisp
as its extention language.
.br
There is not connection between
.I bemacs
and GNU Emacs, except conceptually.

.SH AUTHOR 
Barry Scott
.br
External mail: barry@barrys-emacs.org
.SH SEE ALSO
HTML documentation in file:/opt/corp/contrib/pkg/bemacs/docs/emacs_documentation.html
