#!/bin/sh
target=$HOME/bemacs/kit
find obj -perm -+x -and -type f

cd obj
for f in *.dat *.pag *.dir *.ml emacs.xkeys
do
	echo Installing data file $f in $target
	cp -f $f $target
	chmod o=r,g=r,o=r $target
done

for f in dbadd dbcreate dblist mll-2-db dbdel dbprint bemacs
do
	echo Installing image $f in $target
	cp -f $f $target
	chmod o=rx,g=rx,o=rx $target/$f
done


f=bemacs_server_static
t=bemacs_server

echo Installing image $f in $target/$t
cp -f $f $target/$t
chmod o=rx,g=rx,o=rx $target/$t

