"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

setup(
    app =           ['be_main.py'],
    data_files =    [],
    options =       {'py2app': {
                        'argv_emulation':   True,
                        'iconfile':         'bemacs.icns',
                        'plist':            dict( CFBundleDocumentTypes=
                                                [dict(  CFBundleTypeExtensions=["qqq"],
                                                        CFBundleTypeName="Text Document",
                                                        CFBundleTypeRole="Editor")
                                                ,dict(  CFBundleTypeExtensions=["txt"],
                                                        CFBundleTypeName="Text Document",
                                                        CFBundleTypeRole="Editor"),] ),
                        }},
    setup_requires =['py2app'],
)
