.TH bemacs-cli 1 "26 Dec 2022" "" "bemacs-cli man page"
.SH NAME
bemacs-cli \- Barry's Emacs
.SH SYNOPSIS
Barry's Emacs is a text editor in the Emacs tradition.

.SH DESCRIPTION
Barry's Emacs is a text editor in the Emacs tradition.

bemacs-cli is the terminal version of bemacs.
Use bemacs for the GUI version of bemacs.

Detailed help is available as HTML that is installed in:

file:///usr/share/doc/bemacs/user_guide.html

.SH OPTIONS
TBD

.SH CONTACT
Barry's Emacs main web site if https://barrys-emacs.org

Discussions are on https://groups.io/g/barrys-emacs

Source code is hosted at https://github.com/barry-scott/BarrysEmacs

.SH AUTHOR
Barry Scott (barry@barrys-emacs.org)
