/*	DLG codes	*/
#define	DLG_SWITCHBUFFER	1000
#define DLG_ABOUT                   1001
#define DLG_ERROR                   1002
#define DLG_YESORNO                 1003
#define DLG_FIND                    1004
#define DLG_REPLACE                 1005

/*	About		*/
#define	ID_CODE			100
#define	ID_ALLOC		101
#define	ID_SWITCHBUFFER		200
#define ID_VERSION                  102
#define ID_YES                      6
#define ID_NO                       7
#define ID_REPLACE_WITH             304
#define ID_RE_SEARCH                305
#define ID_MATCH_CASE               306
#define ID_REPLACE                  307
#define ID_FIND_PREV                308
#define ID_INC_SEARCH               311
#define ID_FIND                     400
#define ID_REPLACE_ALL              312
