//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by WINEMACS.RC
//
#define IDR_MAINFRAME                   2
#define IDR_WINEMATYPE                  3
#define IDD_ABOUTBOX                    100
#define IDD_FIND                        101
#define IDD_SWITCH_BUFFER               102
#define IDD_ERROR                       103
#define IDD_YESORNO                     104
#define IDD_REPLACE                     105
#define IDC_ABOUT_VERSION               106
#define IDD_OPTION_DIRECTORIES          106
#define IDC_ABOUT_MEMORY                107
#define IDC_FIND_NEXT                   107
#define IDD_OPTION_COLOURS              107
#define IDC_FIND_TEXT                   108
#define IDC_OPTDIR_SYS_LOGIN            108
#define IDD_OPTION_PRINTER              108
#define IDC_FILE_PARSE_DISK_C           108
#define IDC_FIND_PREV                   109
#define IDC_OPTDIR_BROWSE               109
#define IDD_OPTION_FILENAME_PARSING     109
#define IDC_FILE_PARSE_DISK_E           109
#define IDC_FIND_RE_SEARCH              110
#define IDC_OPTDIR_EMACS_USER           110
#define IDC_FILE_PARSE_DISK_G           110
#define IDC_FIND_MATCH_CASE             111
#define IDC_OPTDIR_EMACS_LOCAL_LIB      111
#define IDC_FILE_PARSE_DISK_I           111
#define IDC_FIND_INC_SEARCH             112
#define IDC_OPTDIR_EMACS_LIB            112
#define IDC_FILE_PARSE_DISK_K           112
#define IDC_FIND_REPLACE_WITH           113
#define IDC_OPTDIR_EMACS_JOURNAL        113
#define IDC_FILE_PARSE_DISK_M           113
#define IDC_FIND_REPLACE                114
#define IDC_OPTDIR_SYS_SCRATCH          114
#define IDC_FILE_PARSE_DISK_O           114
#define IDC_FIND_REPLACE_ALL            115
#define IDC_OPTDIR_BROWSE2              115
#define IDC_FILE_PARSE_DISK_Q           115
#define IDC_SWITCH_BUFFER               116
#define IDC_STATIC2                     116
#define IDC_OPTDIR_EMACS_CHECKPOINT     116
#define IDC_FILE_PARSE_DISK_S           116
#define IDC_ERROR_CODE                  117
#define IDC_STATIC1                     117
#define IDC_OPTDIR_EMACS_MEMORY         117
#define IDC_FILE_PARSE_DISK_U           117
#define IDC_YESORNO_QUESTION            118
#define IDC_FILE_PARSE_DISK_W           118
#define IDC_OPTDIR_BROWSE3              119
#define IDC_FILE_PARSE_DISK_Y           119
#define IDC_OPTCOL_ITEMLIST             120
#define IDC_OPTDIR_BROWSE5              120
#define IDC_OPTDIR_BROWSE6              121
#define IDC_OPTCOL_SAMPLE               122
#define IDC_OPTDIR_BROWSE7              122
#define IDC_OPTCOL_FOREGROUND           123
#define IDC_OPTDIR_BROWSE8              123
#define IDC_OPTCOL_BACKGROUND           124
#define IDC_OPTDIR_BROWSE4              126
#define IDC_OPTDIR_EMACS_PATH           129
#define IDC_OPTCOL_UNDERLINE            130
#define IDC_OPTCOL_ITALIC               131
#define IDC_PRINT_HEADER_FORMAT         132
#define IDC_PRINTER_FOOTER_FORMAT       133
#define IDC_PRINTER_MARGIN_TOP          134
#define IDC_PRINTER_MARGIN_BOTTOM       136
#define IDC_PRINTER_MARGIN_RIGHT        137
#define IDC_PRINTER_MARGIN_LEFT         138
#define IDC_PRINTER_FONT_NAME           139
#define IDC_PRINTER_FONT_SIZE           140
#define IDC_OPTDIR_ASSUME_VFAT          140
#define IDC_FILE_PARSE_DISK_B           146
#define IDC_FILE_PARSE_DISK_D           147
#define IDC_FILE_PARSE_DISK_F           148
#define IDC_FILE_PARSE_DISK_H           149
#define IDC_FILE_PARSE_DISK_J           150
#define IDC_FILE_PARSE_DISK_L           151
#define IDC_FILE_PARSE_DISK_N           152
#define IDC_FILE_PARSE_DISK_P           153
#define IDC_FILE_PARSE_DISK_R           154
#define IDC_FILE_PARSE_DISK_T           155
#define IDC_FILE_PARSE_DISK_V           156
#define IDC_FILE_PARSE_DISK_X           157
#define IDC_FILE_PARSE_DISK_Z           158
#define IDC_FILE_PARSE_DISK_A           159
#define IDC_COLOR_HELP                  1038
#define ID_SEARCH_FIND                  32768
#define ID_SEARCH_REPLACE               32769
#define ID_SWITCH_BUFFER                32773
#define ID_OPTIONS_FONT                 32780
#define ID_OPTIONS_COLORS               32781
#define ID_OPTIONS_DIRECTORIES          32782
#define ID_STOP_EXECUTION               32785
#define ID_USERMENU_FIRST               32800
#define ID_USERMENU_LAST                32899
#define ID_FILE_SAVE_ENVIRONMENT        32900
#define ID_OPTIONS_PRINTING             32901
#define ID_STATUS_LINE                  32902
#define ID_STATUS_COLUMN                32903
#define	ID_STATUS_REPLACE_MODE		32904
#define ID_OPTIONS_FILE_PARSING         32905
#define	ID_STATUS_READ_ONLY		32906

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        111
#define _APS_NEXT_COMMAND_VALUE         32907
#define _APS_NEXT_CONTROL_VALUE         160
#define _APS_NEXT_SYMED_VALUE           103
#endif
#endif
