#!/bin/sh
exec >/tmp/be.tmp 2>&1
set -x
if [ "$DISPLAY" == "" ]
then
	export DISPLAY=:0.0
fi
osascript -e 'activate application "x11"'

APP_ROOT=${0%/*/*}
# lose the -psvn...
shift
${APP_ROOT}/Resources/bemacs-kit/bemacs "$@"
